### ISSUE TITLE
Create str32 class

### ISSUE THREAD

**Issue by Degreezee** [RusGol718/Ural_CS#6]

**Comment by RusGol718** [comment]
Also rearrange natch16/32/64 and celch16/32/64 as follows:

                                   VOID
                                       |
                                celch32
                                      ^
                   celch16       |     celch64
                                       |
                                natch32
                                      ^
                        natch16   natch64

**Comment by RusGol718** [comment]
Done in V2.0.7 and image added in V2.0.7.0.1
